### ISSUE TITLE
Broken isResolved

### ISSUE THREAD

**Issue by TimothyGu** [alwinb/spec-url#1]
See https://github.com/alwinb/spec-url/blob/8ca6faeff8619bb0aef4894eae4562656d73fbd1/src/index.js#L33-L36

The `ord (r)` should probably be `ord (url)`, and `r.hash` should probably be `url.hash`.

**Comment by alwinb** [comment]
Thank you, you are right.

**Comment by alwinb** [comment]
I've released a patch version 1.1.1 which should correct this issue.
