### ISSUE TITLE
Export tags, or change exported ord API

### ISSUE THREAD

**Issue by TimothyGu** [alwinb/spec-url#2]
The exported ord function returns a numeric code for the type of token. However, this code is useless without the associated `tags` map. We should either export `tags`, or make the exported `ord` function return a string.

**Comment by alwinb** [comment]
For version 1.1.1 I have chosen to export a map `ords` to correspond to the token-types in the spec/ model, whilst keeping the (somewhat misnamed) `tags` map private. 

It is not idiomatic to export numeric constants like these, but I want to keep things as simple as possible, and being able to do e.g. `ord (url1) < ord (url2)` is pleasant.
