### ISSUE TITLE
Should forceResolve force its operand?

### ISSUE THREAD

**Issue by TimothyGu** [alwinb/spec-url#4]
https://github.com/alwinb/spec-url/blob/8ca6faeff8619bb0aef4894eae4562656d73fbd1/src/index.js#L136-L137

The [spec](https://alwinb.github.io/url-specification/#reference-resolution) doesn't seem to force the operand though.

**Comment by alwinb** [comment]
It is a change that I made for this library, one that I’ve not yet made in the spec.
