### ISSUE TITLE
package.json name has a leading space

### ISSUE THREAD

**Issue by TimothyGu** [alwinb/spec-url#5]
It looks like the package.json of this package has a leading space:

https://github.com/alwinb/spec-url/blob/8ca6faeff8619bb0aef4894eae4562656d73fbd1/package.json#L2

Is this intentional? It's preventing me from installing the package through Yarn.

**Comment by alwinb** [comment]
That is not intentional, it is just a mistake. Thank you for catching these, I'll patch it up.
